AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'config.ru'
    - 'Guardfile'
    - 'Rakefile'
    - 'Gemfile'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false